-- Seed 37 audio channels with neuroscience-based configurations
-- Each channel has specific brain type affinities and neuroscience tags

INSERT INTO audio_channels (channel_number, channel_name, description, brain_type_affinity, neuroscience_tags) VALUES
(1, 'Deep Focus Alpha', 'Low-frequency binaural beats for sustained concentration', ARRAY['systematic_analyzer', 'structured_achiever'], ARRAY['focus', 'structured', 'calming']),
(2, 'Creative Flow', 'Ambient textures for open-ended thinking', ARRAY['creative_innovator', 'divergent_explorer'], ARRAY['creative', 'flow', 'open']),
(3, 'ADHD Power Mode', 'High-tempo rhythmic patterns for dopamine regulation', ARRAY['divergent_explorer', 'spontaneous_creator'], ARRAY['focus', 'energizing', 'rhythmic']),
(4, 'Calm Productivity', 'Gentle melodic structures for anxiety reduction', ARRAY['sensitive_processor', 'introspective_thinker'], ARRAY['calming', 'focus', 'gentle']),
(5, 'Pattern Recognition', 'Repeating motifs for predictable cognitive anchoring', ARRAY['systematic_analyzer', 'pattern_seeker'], ARRAY['predictable', 'structured', 'analytical']),
(6, 'Social Energizer', 'Upbeat collaborative atmosphere', ARRAY['social_energizer', 'balanced_generalist'], ARRAY['energizing', 'uplifting', 'social']),
(7, 'Deep Work Theta', 'Theta wave entrainment for flow states', ARRAY['introspective_thinker', 'structured_achiever'], ARRAY['focus', 'deep', 'meditative']),
(8, 'Divergent Thinking', 'Unpredictable harmonies for creative problem-solving', ARRAY['creative_innovator', 'divergent_explorer'], ARRAY['creative', 'divergent', 'experimental']),
(9, 'Executive Function', 'Structured progressions for task management', ARRAY['structured_achiever', 'systematic_analyzer'], ARRAY['structured', 'focus', 'organized']),
(10, 'Sensory Comfort', 'Minimal stimulation for sensory sensitivity', ARRAY['sensitive_processor', 'pattern_seeker'], ARRAY['calming', 'gentle', 'minimal']),
(11, 'High Energy Sprint', 'Fast-paced for short bursts of productivity', ARRAY['spontaneous_creator', 'social_energizer'], ARRAY['energizing', 'fast', 'motivating']),
(12, 'Analytical Precision', 'Precision-tuned frequencies for detail work', ARRAY['systematic_analyzer', 'introspective_thinker'], ARRAY['analytical', 'focus', 'precise']),
(13, 'Emotional Regulation', 'Soothing progressions for mood stability', ARRAY['sensitive_processor', 'balanced_generalist'], ARRAY['calming', 'stabilizing', 'gentle']),
(14, 'Hyperfocus Catalyst', 'Intense concentration support for ADHD brains', ARRAY['divergent_explorer', 'spontaneous_creator'], ARRAY['focus', 'intense', 'engaging']),
(15, 'Systematic Order', 'Highly structured for ASD preference patterns', ARRAY['pattern_seeker', 'systematic_analyzer'], ARRAY['predictable', 'structured', 'ordered']),
(16, 'Ambient Exploration', 'Spacious soundscapes for open creativity', ARRAY['creative_innovator', 'introspective_thinker'], ARRAY['creative', 'spacious', 'ambient']),
(17, 'Balanced Baseline', 'Neutral starting point for all brain types', ARRAY['balanced_generalist'], ARRAY['balanced', 'neutral', 'versatile']),
(18, 'Morning Activation', 'Gentle energy increase for day startup', ARRAY['balanced_generalist', 'social_energizer'], ARRAY['energizing', 'uplifting', 'morning']),
(19, 'Afternoon Sustain', 'Mid-day energy maintenance', ARRAY['structured_achiever', 'balanced_generalist'], ARRAY['focus', 'sustaining', 'steady']),
(20, 'Evening Wind-Down', 'Gradual energy decrease for task completion', ARRAY['sensitive_processor', 'introspective_thinker'], ARRAY['calming', 'gentle', 'evening']),
(21, 'Problem Solver', 'Complex patterns for analytical challenges', ARRAY['systematic_analyzer', 'pattern_seeker'], ARRAY['analytical', 'complex', 'problem-solving']),
(22, 'Rhythmic Drive', 'Strong beats for momentum maintenance', ARRAY['social_energizer', 'spontaneous_creator'], ARRAY['rhythmic', 'energizing', 'driving']),
(23, 'Quiet Contemplation', 'Minimal audio for deep thought', ARRAY['introspective_thinker', 'sensitive_processor'], ARRAY['quiet', 'minimal', 'contemplative']),
(24, 'Novelty Seeking', 'Ever-changing patterns for boredom prevention', ARRAY['divergent_explorer', 'creative_innovator'], ARRAY['varied', 'engaging', 'novel']),
(25, 'Comfort Zone', 'Familiar patterns for cognitive ease', ARRAY['pattern_seeker', 'balanced_generalist'], ARRAY['comfortable', 'familiar', 'safe']),
(26, 'Peak Performance', 'Optimized for maximum output periods', ARRAY['structured_achiever', 'systematic_analyzer'], ARRAY['peak', 'optimized', 'intense']),
(27, 'Recovery Mode', 'Restorative frequencies for mental breaks', ARRAY['sensitive_processor', 'balanced_generalist'], ARRAY['restorative', 'gentle', 'recovery']),
(28, 'Collaborative Energy', 'Balanced for team work environments', ARRAY['social_energizer', 'balanced_generalist'], ARRAY['collaborative', 'balanced', 'social']),
(29, 'Solo Deep Dive', 'Isolation-optimized for individual work', ARRAY['introspective_thinker', 'systematic_analyzer'], ARRAY['solo', 'deep', 'focused']),
(30, 'Rapid Switching', 'Quick transitions for multi-tasking', ARRAY['spontaneous_creator', 'divergent_explorer'], ARRAY['dynamic', 'varied', 'flexible']),
(31, 'Single Task Lock', 'Unwavering consistency for mono-focus', ARRAY['structured_achiever', 'pattern_seeker'], ARRAY['consistent', 'locked', 'singular']),
(32, 'Anxiety Buffer', 'Specialized for worry reduction during work', ARRAY['sensitive_processor', 'introspective_thinker'], ARRAY['calming', 'anxiety-reducing', 'safe']),
(33, 'Motivation Boost', 'Dopamine-friendly reward signaling', ARRAY['divergent_explorer', 'spontaneous_creator'], ARRAY['motivating', 'rewarding', 'uplifting']),
(34, 'Sensory Regulation', 'ASD-optimized for sensory management', ARRAY['pattern_seeker', 'systematic_analyzer'], ARRAY['regulating', 'predictable', 'stable']),
(35, 'Innovation Lab', 'Maximum creativity and ideation support', ARRAY['creative_innovator', 'divergent_explorer'], ARRAY['creative', 'innovative', 'experimental']),
(36, 'Learning Mode', 'Optimized for information retention', ARRAY['balanced_generalist', 'systematic_analyzer'], ARRAY['learning', 'retention', 'educational']),
(37, 'Endurance Marathon', 'Extended session support for long hauls', ARRAY['structured_achiever', 'introspective_thinker'], ARRAY['endurance', 'sustained', 'long-duration'])
ON CONFLICT (channel_number) DO NOTHING;
